#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: dj-dadoudou # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  namespace: default
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: 
    src: ./
    exclude:
      - '*.!(js|json)'
      - 'package-lock.json'
      - 'ql.js'
      - 'jd_CheckCK.js'
  handler: index.main_handler #入口
  runtime: Nodejs14.18 # 运行环境 默认 Nodejs12.16
  region: ap-guangzhou # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 900 # 超时时间，单位秒
  asyncRunEnable: true # 是否启用异步执行
  traceEnable: true
  retryNum: 0
  events: #触发器
    - timer:
        parameters:
          name: config
          cronExpression: "0 0 * * * * *"
          enable: true
          argument: config
    - timer: #超市蓝币兑换
        parameters:
          name: blueCoin
          cronExpression: "0 59 23 * * * *"
          enable: false
          argument: jd_blueCoin
    - timer:
        parameters:
          name: cfd
          cronExpression: "59 0 0 * * * *"
          enable: true
          argument: jd_cfd
    - timer:
        parameters:
          name: cfd_pearl
          cronExpression: "50 59 * * * * *"
          enable: true
          argument: jd_cfd_pearl_ex
    - timer:
        parameters:
          name: jxmc
          cronExpression: "59 19 0 * * * *"
          enable: true
          argument: jd_jxmc
    - timer:
        parameters:
          name: jd_redrain_half
          cronExpression: "59 29 21,22 * * * *"
          enable: true
          argument: jd_redrain_half
  environment:
    variables: #环境变量
      JD_JOIN_ZLC: false
      TZ: Asia/Shanghai
